# **Dataframes from Panda**
-Dhairya Dave

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Creating dataframes from lists
a=[[100,9.3,14],
   [80,8.9,12],
   [75,7.9,15],
   [100,9.1,20],
   [60,8,2]]
a_df=pd.DataFrame(a,columns=['Marks','CGPA','Package(in LPA)'])
a_df

   Marks  CGPA  Package(in LPA)
0    100   9.3               14
1     80   8.9               12
2     75   7.9               15
3    100   9.1               20
4     60   8.0                2

In [ ]:
# Creating from dictionary
d = {
    "name":["A","B","C","D","e"],
    "marks": [100, 80, 75, 100, 60],
    "cgpa": [9.3, 8.9, 7.9, 9.1, 8.0],
    "package": [14, 12, 15, 20, 2]
}
d_df = pd.DataFrame(d)
d_df.set_index('name',inplace=True)
d_df

      marks  cgpa  package
name
A       100   9.3       14
B        80   8.9       12
C        75   7.9       15
D       100   9.1       20
e        60   8.0        2

In [ ]:
# Uploading CSV file
df=pd.read_csv('/content/drive/MyDrive/Machine Learning/Python codes/Pandas/movies.csv')
df

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

## **Attributes**

In [ ]:
print(df.shape) # gives the shape of dataframe
print("\n")
print(df.head(10))
print("\n")
print(df.tail(3))
print("\n")
print(df.columns)
print("\n")
print(df.dtypes)
print("\n")
print(df.ndim)
print("\n")
print(df.size)
print("\n")
print(df.values)
print("\n")
print(df.info())

(1629, 18)


                                title_x    imdb_id  \
0              Uri: The Surgical Strike  tt8291224
1                         Battalion 609  tt9472208
2  The Accidental Prime Minister (film)  tt6986710
3                       Why Cheat India  tt8108208
4                       Evening Shadows  tt6028796
5                           Soni (film)  tt6078866
6                         Fraud Saiyaan  tt5013008
7                            Bombairiya  tt4971258
8      Manikarnika: The Queen of Jhansi  tt6903440
9                      Thackeray (film)  tt7777196

                                         poster_path  \
0  https://upload.wikimedia.org/wikipedia/en/thum...
1                                                NaN
2  https://upload.wikimedia.org/wikipedia/en/thum...
3  https://upload.wikimedia.org/wikipedia/en/thum...
4                                                NaN
5  https://upload.wikimedia.org/wikipedia/en/thum...
6  https://upload.wikimedia.org/wikipedia/en/thum...
7  https://upload.wikimedia.org/wikipedia/en/thum...
8  https://upload.wikimedia.org/wikipedia/en/thum...
9  https://upload.wikimedia.org/wikipedia/en/thum...

                                           wiki_link  \
0  https://en.wikipedia.org/wiki/Uri:_The_Surgica...
1        https://en.wikipedia.org/wiki/Battalion_609
2  https://en.wikipedia.org/wiki/The_Accidental_P...
3      https://en.wikipedia.org/wiki/Why_Cheat_India
4      https://en.wikipedia.org/wiki/Evening_Shadows
5          https://en.wikipedia.org/wiki/Soni_(film)
6        https://en.wikipedia.org/wiki/Fraud_Saiyaan
7           https://en.wikipedia.org/wiki/Bombairiya
8  https://en.wikipedia.org/wiki/Manikarnika:_The...
9     https://en.wikipedia.org/wiki/Thackeray_(film)

                            title_y                    original_title  \
0          Uri: The Surgical Strike          Uri: The Surgical Strike
1                     Battalion 609                     Battalion 609
2     The Accidental Prime Minister     The Accidental Prime Minister
3                   Why Cheat India                   Why Cheat India
4                   Evening Shadows                   Evening Shadows
5                              Soni                              Soni
6                     Fraud Saiyaan                     Fraud Saiyyan
7                        Bombairiya                        Bombairiya
8  Manikarnika: The Queen of Jhansi  Manikarnika: The Queen of Jhansi
9                         Thackeray                         Thackeray

   is_adult  year_of_release runtime                  genres  imdb_rating  \
0         0             2019     138        Action|Drama|War          8.4
1         0             2019     131                     War          4.1
2         0             2019     112         Biography|Drama          6.1
3         0             2019     121             Crime|Drama          6.0
4         0             2018     102                   Drama          7.3
5         0             2018      97                   Drama          7.2
6         0             2019     109            Comedy|Drama          4.2
7         0             2019     104      Comedy|Crime|Drama          4.3
8         0             2019     148  Action|Biography|Drama          6.5
9         0             2019     120         Biography|Drama          5.1

   imdb_votes                                              story  \
0       35112  Divided over five chapters  the film chronicle...
1          73  The story revolves around a cricket match betw...
2        5549  Based on the memoir by Indian policy analyst S...
3        1891  The movie focuses on existing malpractices in ...
4         280  While gay rights and marriage equality has bee...
5        1595  Soni  a young policewoman in Delhi  and her su...
6         504  Fraud Saiyyan is the story of a con artist in ...
7         295  It follows the story of Meghna  who gets embro...
8        7361  Manikarnika born in Varanasi when Dixt a minis...
9        2301  Balasaheb Thackrey works as a cartoonist for a...

                                             summary  \
0  Indian army special forces execute a covert op...
1  The story of Battalion 609 revolves around a c...
2  Explores Manmohan Singh's tenure as the Prime ...
3  The movie focuses on existing malpractices in ...
4  Under the 'Evening Shadows'  truth often plays...
5  While fighting crimes against women in Delhi  ...
6  Fraud Saiyyan is the story of a con artist in ...
7  It follows the story of Meghna  who gets embro...
8  Story of Rani Lakshmibai  one of the leading f...
9  Biographical account of Shiv Sena Supremo  Bal...

                                 tagline  \
0                                    NaN
1                                    NaN
2                                    NaN
3                                    NaN
4                                    NaN
5                                    NaN
6                                    NaN
7  They didn't mean to change the world.
8                                    NaN
9                                    NaN

                                              actors        wins_nominations  \
0  Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...                  4 wins
1  Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...                     NaN
2  Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...                     NaN
3  Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...                     NaN
4  Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...  17 wins & 1 nomination
5  Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...  3 wins & 5 nominations
6  Arshad Warsi|Saurabh Shukla|Flora Saini|Sara L...                     NaN
7  Radhika Apte|Akshay Oberoi|Siddhanth Kapoor|Ra...                     NaN
8  Kangana Ranaut|Rimi Sen|Atul Kulkarni|Nalneesh...                     NaN
9  Nawazuddin Siddiqui|Amrita Rao|Abdul Quadir Am...                     NaN

              release_date
0    11 January 2019 (USA)
1  11 January 2019 (India)
2    11 January 2019 (USA)
3    18 January 2019 (USA)
4  11 January 2019 (India)
5    18 January 2019 (USA)
6  18 January 2019 (India)
7  18 January 2019 (India)
8    25 January 2019 (USA)
9  25 January 2019 (India)


              title_x     imdb_id  \
1626  Sabse Bada Sukh   tt0069204
1627            Daaka  tt10833860
1628         Humsafar   tt2403201

                                            poster_path  \
1626                                                NaN
1627  https://upload.wikimedia.org/wikipedia/en/thum...
1628  https://upload.wikimedia.org/wikipedia/en/thum...

                                          wiki_link          title_y  \
1626  https://en.wikipedia.org/wiki/Sabse_Bada_Sukh  Sabse Bada Sukh
1627            https://en.wikipedia.org/wiki/Daaka            Daaka
1628         https://en.wikipedia.org/wiki/Humsafar         Humsafar

       original_title  is_adult  year_of_release runtime         genres  \
1626  Sabse Bada Sukh         0             2018      \N   Comedy|Drama
1627            Daaka         0             2019     136         Action
1628         Humsafar         0             2011      35  Drama|Romance

      imdb_rating  imdb_votes  \
1626          6.1          13
1627          7.4          38
1628          9.0        2968

                                                  story  \
1626  Village born Lalloo re-locates to Bombay  and ...
1627  Shinda tries robbing a bank so he can be wealt...
1628  Sara and Ashar are childhood friends who share...

                                                summary tagline  \
1626  Village born Lalloo re-locates to Bombay  and ...     NaN
1627  Shinda tries robbing a bank so he can be wealt...     NaN
1628  Ashar and Khirad are forced to get married due...     NaN

                                                 actors wins_nominations  \
1626  Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...              NaN
1627                          Gippy Grewal|Zareen Khan|              NaN
1628                                        Fawad Khan|              NaN

               release_date
1626                    NaN
1627  1 November 2019 (USA)
1628  TV Series (2011–2012)


Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')


title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object


2


29322


[['Uri: The Surgical Strike' 'tt8291224'
  'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/URI_-_New_poster.jpg/220px-URI_-_New_poster.jpg'
  ...
  'Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Gautam|Kirti Kulhari|Rajit Kapoor|Ivan Rodrigues|Manasi Parekh|Swaroop Sampat|Riva Arora|Yogesh Soman|Fareed Ahmed|Akashdeep Arora|Kallol Banerjee|'
  '4 wins' '11 January 2019 (USA)']
 ['Battalion 609' 'tt9472208' nan ...
  'Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elena Kazan|Vishwas Kini|Major Kishore|Jashn Kohli|Rammy C. Pandey|Manish Sharma|Sparsh Sharma|Farnaz Shetty|Vikas Shrivastav|Chandraprakash Thakur|Brajesh Tiwari|'
  nan '11 January 2019 (India)']
 ['The Accidental Prime Minister (film)' 'tt6986710'
  'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/The_Accidental_Prime_Minister_film.jpg/220px-The_Accidental_Prime_Minister_film.jpg'
  ...
  'Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul Sharma|Manoj Anand|Arjun Mathur|Suzanne Bernert|Abdul Quadir Amin|Bharat Mistri|Divya Seth|Anil Rastogi|Ramesh Bhatkar|Parrgash Kaur|Jess Kaur|'
  nan '11 January 2019 (USA)']
 ...
 ['Sabse Bada Sukh' 'tt0069204' nan ...
  'Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpal Dutt|Meeta Faiyyaz|Rabi Ghosh|Tarun Ghosh|Sanjeev Kumar|Keshto Mukherjee|Meena Rai|'
  nan nan]
 ['Daaka' 'tt10833860'
  'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Daaka.jpg/220px-Daaka.jpg'
  ... 'Gippy Grewal|Zareen Khan|' nan '1 November 2019 (USA)']
 ['Humsafar' 'tt2403201'
  'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png'
  ... 'Fawad Khan|' nan 'TV Series (2011–2012)']]


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB
None

In [ ]:
df.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [ ]:
# Mathematical Tools

print(a_df)
print("\n")
print(a_df.sum()) # coloumn wise sum
print("\n")
print(a_df.sum(axis=1)) # row wise sum

   Marks  CGPA  Package(in LPA)
0    100   9.3               14
1     80   8.9               12
2     75   7.9               15
3    100   9.1               20
4     60   8.0                2


Marks              415.0
CGPA                43.2
Package(in LPA)     63.0
dtype: float64


0    123.3
1    100.9
2     97.9
3    129.1
4     70.0
dtype: float64

In [ ]:
# Selecting sigle/multiple coloumns

print(a_df['Marks']) # series in type
print("\n")
print(a_df[['Marks','Package(in LPA)']]) #dataframe in type

0    100
1     80
2     75
3    100
4     60
Name: Marks, dtype: int64


   Marks  Package(in LPA)
0    100               14
1     80               12
2     75               15
3    100               20
4     60                2

In [ ]:
# Selecting row using iloc and loc
print(d_df.iloc[0],"\n")
print(d_df.iloc[0:2],"\n")
print(d_df.iloc[-1],"\n")  # print last row
print(d_df.loc['A'],"\n")  # use the index value
print(d_df.loc['A':'D'],"\n")


#Searching both rows and cols
d_df.iloc[0:3,0:2]

marks      100.0
cgpa         9.3
package     14.0
Name: A, dtype: float64

      marks  cgpa  package
name
A       100   9.3       14
B        80   8.9       12

marks      60.0
cgpa        8.0
package     2.0
Name: e, dtype: float64

marks      100.0
cgpa         9.3
package     14.0
Name: A, dtype: float64

      marks  cgpa  package
name
A       100   9.3       14
B        80   8.9       12
C        75   7.9       15
D       100   9.1       20

      marks  cgpa
name
A       100   9.3
B        80   8.9
C        75   7.9

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [ ]:
# Changing the datatype
df["year_of_release"]=df["year_of_release"].astype("int32")
df.info()
# Hence, we reduced the 7KB space ie almost 3%

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int32
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int32(1), int64(2), object(14)
memory usage: 222.8+ KB

In [ ]:
# Value_counts: counts the frequency of rows

#df.value_counts()

In [ ]:
# Drop the Null Values
# in dataframe, it deletes the row if any coloumn in that row has Null value
print("The original size: ",df.shape) # originally it was 1629 rows
#df=df.dropna() # using this will lead to permanent change in the data #288
print("The new size: ",df.shape)
df=df.dropna(how="all") # drops that row which has all as Null value
df.shape #1629
df=df.dropna(subset=["poster_path","actors"])
df.shape #1524

The original size:  (1629, 18)
The new size:  (1629, 18)

(1524, 18)

In [ ]:
# FIllna
df["wins_nominations"] = df["wins_nominations"].fillna("Unknown")
df[df["wins_nominations"]=="Unknown"].head(4)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,Unknown,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,Unknown,18 January 2019 (USA)
6,Fraud Saiyaan,tt5013008,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Fraud_Saiyaan,Fraud Saiyaan,Fraud Saiyyan,0,2019,109,Comedy|Drama,4.2,504,Fraud Saiyyan is the story of a con artist in ...,Fraud Saiyyan is the story of a con artist in ...,NaN,Arshad Warsi|Saurabh Shukla|Flora Saini|Sara L...,Unknown,18 January 2019 (India)
7,Bombairiya,tt4971258,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bombairiya,Bombairiya,Bombairiya,0,2019,104,Comedy|Crime|Drama,4.3,295,It follows the story of Meghna who gets embro...,It follows the story of Meghna who gets embro...,They didn't mean to change the world.,Radhika Apte|Akshay Oberoi|Siddhanth Kapoor|Ra...,Unknown,18 January 2019 (India)